{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mimir-cardicop.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mimir-cardicop.labels" . | nindent 4 }}
{{- end }}