apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir-cardicop.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mimir-cardicop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: metrics
  selector:
    {{- include "mimir-cardicop.selectorLabels" . | nindent 4 }}
  type: ClusterIP